feat(SME): expose available connectors for the platform
gravitee-io/old-gravitee-api-management pull request #108
Opened 2021-09-21 13:04 UTC by brasseld

gravitee-io/issues#6132

2021-10-19 15:39 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-levbhuckog.chromatic.com)

2021-10-19 15:40 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-19 16:01 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-piokinnwyk.chromatic.com)

2021-10-19 16:02 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-20 09:19 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-uttsdatjoj.chromatic.com)

2021-10-20 09:22 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-20 13:33 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-alwhktixrw.chromatic.com)

2021-10-20 13:35 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-20 15:25 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-fxnkemqgpr.chromatic.com)

2021-10-20 15:27 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-21 14:13 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-ypgwnldrln.chromatic.com)

2021-10-21 14:15 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-21 16:43 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-eypqhevimc.chromatic.com)

2021-10-21 16:44 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-21 17:13 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-zgtdimtprw.chromatic.com)

2021-10-21 17:16 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-25 05:45 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-vgacpyyapm.chromatic.com)

2021-10-25 05:48 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-25 06:03 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-egiucivhiu.chromatic.com)

2021-10-25 06:05 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-25 13:05 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-rbqesoabcf.chromatic.com)

2021-10-25 13:08 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-26 06:02 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-ifcyactgtc.chromatic.com)

2021-10-26 06:05 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-26 10:39 UTC, phiz71 requested changes

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorResource.java
> +    @ApiOperation(value = "Get a connector", notes = "User must have the MANAGEMENT_API[READ] permission to use this service")
```suggestion
    @ApiOperation(value = "Get a connector", notes = "User must have the ENVIRONMENT_API[READ] permission to use this service")
```

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorResource.java
> +    @ApiOperation(value = "Get a connector's schema", notes = "User must have the MANAGEMENT_API[READ] permission to use this service")
```suggestion
    @ApiOperation(value = "Get a connector's schema", notes = "User must have the ENVIRONMENT_API[READ] permission to use this service")
```

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorResource.java
> +        notes = "User must have the MANAGEMENT_API[READ] permission to use this service"
```suggestion
        notes = "User must have the ENVIRONMENT_API[READ] permission to use this service"
```

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorsResource.java
> +    @ApiOperation(value = "List connector plugins", notes = "User must have the MANAGEMENT_API[READ] permission to use this service")
```suggestion
    @ApiOperation(value = "List connector plugins", notes = "User must have the ENVIRONMENT_API[READ] permission to use this service")
```

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorsResource.java
> +            @ApiResponse(code = 200, message = "List of connectors", response = ResourceListItem.class, responseContainer = "List"),
```suggestion
            @ApiResponse(code = 200, message = "List of connectors", response = ConnectorListItem.class, responseContainer = "List"),
```

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorResource.java
> +    public String getConnectorSchema(@PathParam("connector") String connector) {
Add `ApiResponses` annotation

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConnectorResource.java
> +    public String getConnectorDoc(@PathParam("connector") String connector) {
Add `ApiResponses` annotation

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/JsonSchemaServiceImpl.java
> +            Schema schemaa = SchemaLoader
schema**a**

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/JsonSchemaServiceImpl.java
> +            Pattern pattern = Pattern.compile("\\[(.*?)\\]");
compile this pattern at class level to avoid pattern compilation at each call.

2021-10-26 10:39 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/JsonSchemaServiceTest.java
> +    }
one test use "regex" format and the other one "java-regex", is it desired ?

2021-10-26 14:29 UTC, gcusnieux commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/JsonSchemaServiceTest.java
> +    }
Yes, java-regex is for retro compatibility

2021-10-26 17:00 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here]()

2021-10-26 17:03 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-26 18:30 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-rmventifwq.chromatic.com)

2021-10-26 18:32 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-27 07:03 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-oeexnpdiuj.chromatic.com)

2021-10-27 07:05 UTC, phiz71 approved these changes

2021-10-27 07:10 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-iddhfecvoa.chromatic.com)

2021-10-27 07:11 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-27 07:25 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-dyplzhhvgu.chromatic.com)

2021-10-27 07:28 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-27 09:25 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-murlyigkwd.chromatic.com)

2021-10-27 09:27 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-27 09:37 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-hfksoblxhl.chromatic.com)

2021-10-27 09:39 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-6132-connector-sme/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-10-27 09:44 UTC, merged