Merge 3.5.x
gravitee-io/old-gravitee-api-management pull request #286
Opened 2021-11-22 16:21 UTC by gaetanmaisse

**Issue**

https://github.com/gravitee-io/issues/issues/6140

**Description**

A small description of what you did in that PR.

**Additional context**

2021-11-22 16:28 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-22 17:05 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-24 09:05 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-24 10:53 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-24 11:00 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-24 13:43 UTC, ThibaudAV approved these changes
🤞

2021-11-24 14:03 UTC, phiz71 requested changes

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                        export GATEWAY_IMAGE_TAG=graviteeio.azurecr.io/apim-management-api:${TAG}
```suggestion
                        export GATEWAY_IMAGE_TAG=graviteeio.azurecr.io/apim-gateway:${TAG}
```

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                          docker login --username="${DOCKERHUB_BOT_USER_NAME}" -p="${DOCKERHUB_BOT_USER_TOKEN}"
To fix, like on master

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                        if [[ $CIRCLE_BRANCH =~ ^([0-9]+\.[0-9]+\.x|master)$ ]]
To fix, like on master

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                        if [[ $CIRCLE_BRANCH =~ ^([0-9]+\.[0-9]+\.x|master)$ ]]
To fix, like on master

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                                         --set "gateway.image.tag=${TAG}"
Don't the forget the "hack" with redis-repository
https://github.com/gravitee-io/gravitee-gateway/blob/3.13.x/.circleci/config.yml#L210

2021-11-24 14:03 UTC, phiz71 commented on .circleci/config.yml
> +                                     --set "gateway.image.tag=${TAG}"
Don't forget the "hack" with redis-repository
https://github.com/gravitee-io/gravitee-gateway/blob/3.13.x/.circleci/config.yml#L210

2021-11-24 14:03 UTC, phiz71 commented on gravitee-apim-gateway/GIT_COMMIT
> +565d72f88a868053132f2750f3faeb2a2fb142f6
necessary ?

2021-11-24 15:59 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-25 08:00 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-25 10:41 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-25 10:51 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/merge-3-5-x/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-25 11:01 UTC, merged