test: consolidated all tests into integration folder
gravitee-io/old-gravitee-api-management pull request #307
Opened 2021-11-24 21:06 UTC by ctschacher

**Description**

- All tests consolidated into a single folder ('integration')
- Added env variables in cypress config for e2e tests

This PR replaces the old one (https://github.com/gravitee-io/gravitee-api-management/pull/288). It will be deleted later on.

2021-11-24 21:08 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-lcddziupvg.chromatic.com)

2021-11-24 21:10 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/test-consolidate-test-folder/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-25 10:18 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-islcczgtgn.chromatic.com)

2021-11-25 10:19 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/test-consolidate-test-folder/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-26 07:36 UTC, ytvnr requested changes

2021-11-26 07:36 UTC, ytvnr commented on gravitee-apim-cypress/cypress.json
> +  "integrationFolder": "cypress/integration",
as said during our meeting this line will imply that all the tests in `integration` will be executed.

and I don't think we want to mix

in my opinion:

- [ ] remove `cypress.json` at root level
- [ ] add a `cypress-config.json` in cypress/integration/nrt
- [ ] change commands in `package.json` to use this new config file

2021-11-29 13:58 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-rhylrapsfn.chromatic.com)

2021-11-29 13:59 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/test-consolidate-test-folder/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-29 14:14 UTC, ctschacher commented on gravitee-apim-cypress/cypress.json
> +  "integrationFolder": "cypress/integration",
Alright, I did these changes and updated branch.

2021-11-29 15:45 UTC, ytvnr approved these changes
looks good to me !

2021-11-29 15:45 UTC, ytvnr commented on gravitee-apim-cypress/package.json
> +        "test": "cypress open",
you can delete this line

2021-11-30 14:53 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-knoouxguch.chromatic.com)

2021-11-30 14:55 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/test-consolidate-test-folder/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

2021-11-30 15:25 UTC, merged