fix: Performance improvements
gravitee-io/old-gravitee-api-management pull request #58
Opened 2021-08-31 14:38 UTC by brasseld

Closes gravitee-io/issues#6066

2021-09-06 11:07 UTC, leleueri reviewed
Fields picture & background are excluded from Mongo repository result but I can't see the same in the JDBC implementation.

2021-09-06 11:07 UTC, leleueri commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
> +                    logger.error("Parsing error for API id[{}]: ", apiId, sde.getMessage());
missing `{}` for the exception message

2021-09-06 11:07 UTC, leleueri commented on gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-subscriptions/src/main/java/io/gravitee/rest/api/services/subscriptions/ScheduledSubscriptionsService.java
> +    @Value("${services.subscriptions.cron:0 1 * * * *}")
Because the default value has changed, should we inform about this change in a ChangeLogs/Migration guide?

2021-09-06 11:11 UTC, leleueri requested changes
-     Fields picture & background are excluded from Mongo repository result but I can't see the same in the JDBC implementation.
-     Some Junit Tests fail

2021-10-04 20:14 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
> +                    logger.error("Parsing error for API id[{}]: ", apiId, sde.getMessage());
fixed

2021-10-04 20:36 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-subscriptions/src/main/java/io/gravitee/rest/api/services/subscriptions/ScheduledSubscriptionsService.java
> +    @Value("${services.subscriptions.cron:0 1 * * * *}")
PR added : https://github.com/gravitee-io/release/pull/353

2021-10-04 21:19 UTC, phiz71 approved these changes

2021-10-05 05:47 UTC, gcusnieux approved these changes

2021-10-05 09:58 UTC, phiz71 approved these changes

2021-10-05 09:59 UTC, merged