Feat/6006 handle duplicate api keys
gravitee-io/old-gravitee-api-management pull request #82
Opened 2021-09-10 07:39 UTC by marcambier

https://github.com/gravitee-io/issues/issues/6006

Now we permit multiple API Keys with same key.
To find the unique one, we have to search with two criterias : key and api.

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +        LOGGER.debug("JdbcApiKeyRepository.findByKey([key])");
why this change ? I think it's a little confusing to see a log with `JdbcApiKeyRepository.findByKey([key])`. We may think it's an array. Maybe we can just replace it by '****' chars, so we know that this data is hidden ?
wdyt ?

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +        LOGGER.debug("JdbcApiKeyRepository.findByKeyAndApi([key], {})", api);
same remark.

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +                    new String[] { key, api }
use varargs :)
```suggestion
                .query(
                    getOrm().getSelectAllSql() + " where " + escapeReservedWord("key") + " = ? and api = ?",
                    getOrm().getRowMapper(),
                    key,
                    api
```

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
> +        return internalApiKeyRepo.findById(id).map(apiKey -> mapper.map(apiKey, ApiKey.class));
do not forget to update `create-index.js` in repository-mongodb and add a note in release repository to update indices.

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
> +        return internalApiKeyRepo.findByKeyAndApi(key, api).stream().findFirst().map(apiKey -> mapper.map(apiKey, ApiKey.class));
maybe like Jdbc repositories you can add some log precising we enter the method ?

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
> +    }
is EnvironmentResource the best place to add this resource ? 
Maybe it should be under ApplicationResource since an ApiKey will belong to only one application ? (just to chipoting a little)

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/KeyResource.java
> +        if (apiKey.getId() != null && !key.equals(apiKey.getId())) {
I don't know if you authorize apiKey.id to be null when updating, if yes it could just be 
```suggestion
        if (!key.equals(apiKey.getId())) {
```

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/KeyResource.java
> +        apiKey.setId(key);
since you already validate that key.equals(apiKey.getId()) I think you do not need this line ?

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/subscription/SubscriptionQuery.java
> +    }
in my opinion, we should replace .contains by .equals to be more accurate.
wdyt ?

2021-09-15 13:43 UTC, ytvnr commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
> +                        }
```suggestion
                        subscription -> (
                            query.matchesApi(subscription.getApi()) &&
                            query.matchesApplication(subscription.getApplication()) &&
                            query.matchesPlan(subscription.getPlan()) &&
                            query.matchesStatus(subscription.getStatus())
                        )
```

2021-09-15 14:20 UTC, marcambier commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +        LOGGER.debug("JdbcApiKeyRepository.findByKey([key])");
I changed this code in order to stop logging API keys, as it's not a good practice.
I agree, that was confusing and i replaced it with '***'.

2021-09-15 14:20 UTC, marcambier commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +        LOGGER.debug("JdbcApiKeyRepository.findByKeyAndApi([key], {})", api);
I changed this code in order to stop logging API keys, as it's not a good practice.
I agree, that was confusing and i replaced it with '***'.

2021-09-15 14:25 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/subscription/SubscriptionQuery.java
> +    }
In this SubscriptionQuery, apis, plans, applications, and status are lists. that was I use contains.
For example, you can search a subscription using this query, with multiple applications criteria.
And is one of this criteria application match your, matchesApplication("my application") returns true.

OK for you ?

2021-09-15 15:03 UTC, marcambier commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +                    new String[] { key, api }
done

2021-09-15 15:03 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
> +                        }
done

2021-09-15 15:05 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/KeyResource.java
> +        if (apiKey.getId() != null && !key.equals(apiKey.getId())) {
I wanted to keep the same behaviour as existing update endpoint in ApiKeysResource, which is now deprecated.
id is provided in URL, so it's not mandatory in body.
wdyt ?

2021-09-15 16:23 UTC, jhaeyaert requested changes
As discussed together:

- Make sure the required permissions are well check. I'm not sure the `DELETE /keys/{keyId}` is working with non admin user
- Maybe we should re-discuss about `/keys` endpoints vs `/apis/{apiId}/keys` vs `/apis/{apiId}/subscriptions/{subscriptionId}/keys`.
- The current implementation does not allow to use the same api key value when dealing with different environments. We should be able to allow this.

2021-09-17 08:37 UTC, marcambier commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
> +        return internalApiKeyRepo.findById(id).map(apiKey -> mapper.map(apiKey, ApiKey.class));
I added necessary indexes to create_index script.
There were already into the release note migration script;

2021-09-17 08:38 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
> +    }
I refactored apiKeys endpoints. I let you check that in my last commit.

2021-09-17 08:38 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/KeyResource.java
> +        apiKey.setId(key);
I refactored apiKeys endpoints. I let you check that in my last commit.

2021-09-17 08:38 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/KeyResource.java
> +        if (apiKey.getId() != null && !key.equals(apiKey.getId())) {
I refactored apiKeys endpoints. I let you check that in my last commit.

2021-09-17 13:42 UTC, marcambier commented
> As discussed together:
> 
>     * Make sure the required permissions are well check. I'm not sure the `DELETE /keys/{keyId}` is working with non admin user
> 
>     * Maybe we should re-discuss about `/keys` endpoints vs `/apis/{apiId}/keys` vs `/apis/{apiId}/subscriptions/{subscriptionId}/keys`.
> 
>     * The current implementation does not allow to use the same api key value when dealing with different environments. We should be able to allow this.

As discussed together, I refactored the API keys endpoints,
And for the multi-environments behavior, i created a dedicated ticket : https://github.com/gravitee-io/issues/issues/6199

2021-09-17 14:48 UTC, ytvnr approved these changes
lgtm

2021-09-20 15:16 UTC, merged